# Generated by Django 5.2 on 2025-04-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_core', '0002_remove_profile_display_name_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='New User', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
