# Generated by Django 5.2 on 2025-04-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_core', '0003_profile_education_profile_skills_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
