# Generated by Django 5.2 on 2025-04-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
