# Generated by Django 5.2 on 2025-04-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_auth', '0002_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profession_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=11, upload_to='profile_pics/'),
            preserve_default=False,
        ),
    ]
