# Generated by Django 5.2 on 2025-04-14 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_auth', '0004_rename_experience_title_to_job_title'),
    ]

    operations = [
    ]
