# Generated by Django 5.2 on 2025-04-14 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_auth', '0005_convert_skill_proficiency_to_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
    ]
